### ISSUE TITLE
Issues with Test.R

### ISSUE THREAD

**Issue by rudro12356** [UBC-DSCI/data-science-a-first-intro-worksheets#5]
For some reason, whenever I'm trying to run the test for 7.1.2 an error that "solution is incorrect is being shown". I have put the answer in the format "Letter" as asked for in the prompt. I was on Jupyter lab, and have switched to Jupyter notebook but the problem persists. 
However, the test ran fine for the small questions. Could someone please help on this? Thanks!

Instance where test ran succesfully:
![image](https://user-images.githubusercontent.com/61032181/216858690-99325f5d-a375-4022-b5bd-c022ba2a99df.png)

Other screenshots for reference:
![image](https://user-images.githubusercontent.com/61032181/216858468-feaecd3b-313a-4d36-ae02-7c9493c5abd0.png)
![image](https://user-images.githubusercontent.com/61032181/216858560-5b938f85-38e6-4878-91db-d93985bf465f.png)

**Comment by trevorcampbell** [comment]
You forgot to assign your answer to an object named `answer7.1.2`! If you look in the error message, you'll see 

`object answer7.1.2 not found`

**Comment by rudro12356** [comment]
Thank you! I missed that part. I didn't realize it had to be assigned to an object.
